# Disable checkpoint saving but keep rfid callback
rfid:
  _target_: src.callbacks.rfid_callback.RFIDCallback
  rfid_every_n_steps: 20
  rfid_every_epoch: true
  rfid_num_samples: 1000
  rfid_batch_size: 64
  rfid_device: cuda
  rfid_output_dir: logs/rfid_samples
  rfid_save_samples: true
  save_samples_count: 64
  use_train_dataloader: false
  use_full_validation_set: true