_target_: src.callbacks.rfid_callback.RFIDCallback
rfid_every_n_steps: 1000  # Evaluate every 1000 steps
rfid_every_epoch: true  # Evaluate at the end of each epoch
rfid_num_samples: 1000  # Number of samples to use for evaluation (used when use_full_validation_set=false)
rfid_batch_size: 64  # Batch size for FID computation
rfid_device: cuda  # Device to use
rfid_output_dir: logs/rfid_samples  # Directory to save samples
rfid_save_samples: true  # Save sample images
save_samples_count: 64  # Number of sample pairs to save
use_train_dataloader: false  # Do not fall back to train dataloader
use_full_validation_set: true  # Use all samples from validation set for rFID evaluation